# Generated by Django 5.2.4 on 2025-07-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_libro_anio_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(max_length=100),
        ),
    ]
