# Generated by Django 5.2.4 on 2025-07-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_libro_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
